steps:
  - name: adamharrison/firebase-cli
    entrypoint: npm
    args: ['install']
  - name: adamharrison/firebase-cli
    entrypoint: npm
    args: ['run', 'generate']
  - name: adamharrison/firebase-cli
    args: ['deploy', '--project=$PROJECT_ID']

